db_user: "root"
db_password: "patkatebi123"
db_host: "52.24.138.122:3306"
db_name: "raketa"
http_addr: ":8000"
google_oauth_id: "255707941160-otgrloue9tvi1j23sifir5mfh2uctbns.apps.googleusercontent.com"
google_oauth_secret: "FGcfrXPrLyopN_f3nTbgUnpV"
secret: "fmocsi38js4vojcpos3jf9spfjs48"
redis_host: "52.24.138.122:6379"
redis_password: ""
