db_user: "rocket"
db_password: "fkslkfpos48jfso4jfs4hvmxlsap9ew"
db_host: "localhost"
db_name: "rocket"
http_addr: "localhost:8000"
google_oauth_id: "255707941160-otgrloue9tvi1j23sifir5mfh2uctbns.apps.googleusercontent.com"
google_oauth_secret: "FGcfrXPrLyopN_f3nTbgUnpV"
secret: "fmocsi38js4vojcpos3jf9spfjs48"
