export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_GROUP_DAYS = 'GET_GROUP_DAYS';
export const GET_GROUP_DAYS_SUCCESS = 'GET_GROUP_DAYS_SUCCESS';
export const GET_GROUP_DAYS_FAILURE = 'GET_GROUP_DAYS_FAILURE';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const JOIN_GROUP = 'JOIN_GROUP';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_FAILURE = 'JOIN_GROUP_FAILURE';

export const LEAVE_GROUP = 'LEAVE_GROUP';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILURE = 'LEAVE_GROUP_FAILURE';

export const WATCH_GROUP = 'WATCH_GROUP';
export const WATCH_GROUP_SUCCESS = 'WATCH_GROUP_SUCCESS';
export const WATCH_GROUP_FAILURE = 'WATCH_GROUP_FAILURE';

export const UNWATCH_GROUP = 'UNWATCH_GROUP';
export const UNWATCH_GROUP_SUCCESS = 'UNWATCH_GROUP_SUCCESS';
export const UNWATCH_GROUP_FAILURE = 'UNWATCH_GROUP_FAILURE';

export const CREATE_RULE = 'CREATE_RULE';
export const CREATE_RULE_SUCCESS = 'CREATE_RULE_SUCCESS';
export const CREATE_RULE_FAILURE = 'CREATE_RULE_FAILURE';

export const MUTE_RULE = 'MUTE_RULE';
export const MUTE_RULE_SUCCESS = 'MUTE_RULE_SUCCESS';
export const MUTE_RULE_FAILURE = 'MUTE_RULE_FAILURE';

export const UNMUTE_RULE = 'UNMUTE_RULE';
export const UNMUTE_RULE_SUCCESS = 'UNMUTE_RULE_SUCCESS';
export const UNMUTE_RULE_FAILURE = 'UNMUTE_RULE_FAILURE';
